### ISSUE TITLE
[Question] How to test telegram bot?

### ISSUE THREAD

**Issue by simkimsia** [aikchun/totobro-bot#31]
According to this https://github.com/telegraf/telegraf/discussions/1482#discussioncomment-947053, 

I have two options largely:

1. have a separate robot with its own token and webhook
2. use https://github.com/jehy/telegram-test-api

Which do you suggest?

**Comment by aikchun** [comment]
It seems like [telegram-test-api](https://github.com/jehy/telegram-test-api) would be a good long term solution for a project that does serious work, gets maintained for a long time and worked on by more people, which is not what this project is (for now). So I would do manual test with a separate bot token.

I would look into `telegram-test-api` in the future for sure.

**Comment by simkimsia** [comment]
> So I would do manual test with a separate bot token.

👍
